version: '3.8'
services:
  keycloak:
    image: 'bitnami/keycloak'
    ports:
      - "8083:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_DATABASE_NAME=bank-app
      - KEYCLOAK_DATABASE_PASSWORD=admin
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
    depends_on:
      - postgresql

  postgresql:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bank-app'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  adminer:
    image: 'adminer:latest'
    restart: 'always'
    ports:
      - '8082:8080'
    depends_on:
      - postgresql
    environment:
      - 'ADMINER_DESIGN=hydra'
      - 'ADMINER_DEFAULT_SERVER=postgres'
      - 'ADMINER_PLUGINS=tables-filter'

  web:
    image: nginx:1.27.0-alpine
    ports:
      - "8080:80"
    volumes:
      - ./static:/var/www/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
