services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bank-app'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  adminer:
    image: 'adminer:latest'
    restart: 'always'
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    environment:
      - 'ADMINER_DESIGN=hydra'
      - 'ADMINER_DEFAULT_SERVER=postgres'
      - 'ADMINER_PLUGINS=tables-filter'
