server:
  port: 8081
  error:
    include-stacktrace: on_param

spring:
  application:
    name: bank-app-backend

  datasource:
    url: ${BANK_APP_DB_URL:jdbc:postgresql://localhost:5432/bank-app}
    username: ${BANK_APP_DB_USERNAME:postgres}
    password: ${BANK_APP_DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update


  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /api/docs

app:
  security:
    jwt:
      expiration: ${BANK_APP_JWT_EXPIRE:86400000} # 1 day
      secretKey: ${BANK_APP_JWT_SECRET:09B63EE1A5DD4AB080610DDA313625F51E64D38BF4710421F95C447EA0CA46C4}
