server:
  port: 8081
  error:
    include-stacktrace: on_param

spring:
  application:
    name: bank-app-backend

  datasource:
    url: ${BANK_APP_DB_URL:jdbc:postgresql://localhost:5432/bank-app}
    username: ${BANK_APP_DB_USERNAME:postgres}
    password: ${BANK_APP_DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/bank-app

springdoc:
  swagger-ui:
    path: /api/docs
