server:
  port: 8081
  error:
    include-stacktrace: on_param


spring:
  application:
    name: bank-app-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/bank-app
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop


app:
  security:
    jwt:
      expiration: 86400000 # 1 day
      secretKey: 09B63EE1A5DD4AB080610DDA313625F51E64D38BF4710421F95C447EA0CA46C4
